name: wakemeup
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  intl: any
  modal_bottom_sheet: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/images/home/
  - assets/images/store/popular_categories/
  - assets/images/store/campaign/
  - assets/images/store/spotlight/
  fonts:
  - family: AtypText
    fonts:
        - asset: assets/fonts/AtypText-Medium.otf